server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/appdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=app
spring.datasource.password=app


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect